version: 3
services:
  portainer:
    image: portainer/portainer
    ports:
      - "21200:8000"
      - "21201:9000"
    name: portainer
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always

  bastion:
    image: cloudposse/bastion:latest
    ports:
      - "1234:22"
    environment:
      - "DUO_IKEY="
      - "DUO_SKEY="
      - "DUO_HOST="

volumes:
  portainer_data